version: 1
accounts:
- name: alice
  coins:
  - 1000000000000000umycel
  mnemonic: album unlock fence mixture little chest concert limb when melody outdoor tool romance kid throw spread bean exercise squeeze syrup saddle year change alone
- name: bob
  coins:
  - 500000000000000umycel
  mnemonic: holiday coil vicious hunt hybrid maximum post spread stomach input more demise garbage slim mouse relief cage hat interest armed promote nerve craft solar
faucet:
  name: bob
  coins:
  - 100000mycel
client:
  typescript:
    path: typescript/ts-client
  hooks:
    path: typescript/hooks
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000mycel
genesis:
  chain_id: "mycel-local"
  app_state:
    staking:
      params:
        bond_denom: "umycel"
