version: 1
accounts:
- name: alice
  coins:
  - 80000000000000umycel
  mnemonic: album unlock fence mixture little chest concert limb when melody outdoor tool romance kid throw spread bean exercise squeeze syrup saddle year change alone
- name: faucet
  coins:
  - 20000000000000umycel
  mnemonic: holiday coil vicious hunt hybrid maximum post spread stomach input more demise garbage slim mouse relief cage hat interest armed promote nerve craft solar
faucet:
  name: faucet
  coins:
  - 20000000000000umycel
client:
  typescript:
    path: typescript/ts-client
  hooks:
    path: typescript/hooks
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 50000000000000umycel
genesis:
  chain_id: "mycel-shugyo"
  consensus_params:
    block:
      max_bytes: "22020096"
      max_gas: "-1"
  app_state:
    crisis:
      constant_fee:
        denom: umycel
    distribution:
      params:
        community_tax: '0.1'
    gov:
      params:
        min_deposit:
        - amount: '10000000'
          denom: umycel
    mint:
      params:
        mint_denom: umycel
    staking:
      params:
        bond_denom: umycel

